spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/taskmanagement
      database: taskmanagement
  
  application:
    name: task-management-api
  
server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.example.taskmanagement: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/task-management-api.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always